# upload
version: "2"

services:
  web:
    build: .
    image: ctftraining/base_image_nginx_mysql_php_73
    restart: always
    ports:
      - "0.0.0.0:8303:80"
    environment:
      - FLAG=flag{y@4_kn0w_9hp_exten5ion!}